# Generated by Django 5.0.2 on 2024-02-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('pdf_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_analysis_data', models.JSONField(blank=True, null=True)),
                ('dominant_emotion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
